use_frameworks!

target 'RCCollapsibleHeader_Example' do
	platform :ios, '10.0'


	pod 'RCCollapsibleHeader', :path => '../'
	pod 'SwifterSwift'


	target 'RCCollapsibleHeader_Tests' do
		inhibit_all_warnings!
		# inherit! :search_paths

		pod 'Quick', '~> 1.2.0'
		pod 'Nimble', '~> 7.0.2'
		pod 'FBSnapshotTestCase' , '~> 2.1.4'
		pod 'Nimble-Snapshots' , '~> 6.3.0'
	end

	post_install do |installer|
	    installer.pods_project.targets.each do |target|
	        case target.name 
		        when 'Quick', 'Nimble', 'FBSnapshotTestCase', 'Nimble-Snapshots'
		            target.build_configurations.each do |config|
		                config.build_settings['SWIFT_VERSION'] = '4.0'
		            end
		        end
	    end
	end
end
